version: '3.7'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: env/php/Dockerfile
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=ping-stats
    volumes:
      - ./app:/app:delegated
      - ./env/php/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
      - ./data/sqlite:/var/lib/sqlite
    working_dir: /app
    restart: on-failure
    networks:
      - app_network

networks:
  app_network: